version: '3'

services:
  web:
    ports:
    - "443:443"
    - "8443:8443"
    image: nginx:alpine
    restart: always
    volumes:
    - ./var/www/html:/var/www/html
    - ./conf.d:/etc/nginx/conf.d
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./ssl_certificates:/etc/nginx/ssl_certificates
    - ./ssl_keys:/etc/nginx/ssl_keys
    - ./logs:/var/log/nginx
    environment:
      TZ: America/Guayaquil
    links:
    - php
  php:
    image: geminis3/php-fpm-laravel:8.1
    restart: always
    volumes:
    - ./html:/var/www/html
    links:
    - postgres

  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      TZ: America/Guayaquil
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  pgadmin4:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - 8082:80
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bayas.dev
      PGADMIN_DEFAULT_PASSWORD: admin
    links:
    - postgres
