version: '3.8'

services:
  web:
    ports:
    - "80:80"
    - "443:443"
    - "8443:8443"
    image: nginx:latest
    restart: always
    volumes:
    - ./var/www/html:/var/www/html
    - ./conf.d:/etc/nginx/conf.d
    - ./ssl_certificates:/etc/nginx/ssl_certificates
    - ./ssl_keys:/etc/nginx/ssl_keys
    - ./logs:/var/log/nginx
    environment:
      TZ: America/Guayaquil
    links:
    - php
  php:
    image: geminis3/php:fpm-lumen
    restart: always
    volumes:
    - ./var/www/html:/var/www/html
    environment:
      TZ: America/Guayaquil
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:~/.composer/vendor/bin
    links:
    - postgres

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      TZ: America/Guayaquil
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  pgadmin4:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - 8082:80
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bayas.dev
      PGADMIN_DEFAULT_PASSWORD: admin
    links:
    - postgres
